//General Parameters
#define SIM_STEP 1
#define SIM_LEN 10
#define SOC_INIT 1.0
#define VREF_BUS 3.3
#define SELFDISCH_FACTOR 0.0
#define NS 4
#define NP 3
// params for CPU
#define CPU_I_IDLE 0.002
#define CPU_T_ON 6
#define CPU_ON_I_ON 13
//Parameters for sensor air_quality_sensor
#define AIR_QUALITY_SENSOR_BASE_ADDRESS 0
#define AIR_QUALITY_SENSOR_REG_DIMENSION 25
#define AIR_QUALITY_SENSOR_VOLTAGE 3.3
#define AIR_QUALITY_SENSOR_I_ON_READ 49.2
#define AIR_QUALITY_SENSOR_T_ON_READ 30
#define AIR_QUALITY_SENSOR_I_ON_WRITE 48.2
#define AIR_QUALITY_SENSOR_T_ON_WRITE 30
#define AIR_QUALITY_SENSOR_I_IDLE 0.002
//Parameters for sensor temperature_sensor
#define TEMPERATURE_SENSOR_BASE_ADDRESS 26
#define TEMPERATURE_SENSOR_REG_DIMENSION 20
#define TEMPERATURE_SENSOR_VOLTAGE 3.3
#define TEMPERATURE_SENSOR_I_ON_WRITE 0.35
#define TEMPERATURE_SENSOR_T_ON_WRITE 6
#define TEMPERATURE_SENSOR_I_ON_READ 0.3
#define TEMPERATURE_SENSOR_T_ON_READ 6
#define TEMPERATURE_SENSOR_I_IDLE 0.002
//Parameters for sensor methane_sensor
#define METHANE_SENSOR_BASE_ADDRESS 47
#define METHANE_SENSOR_REG_DIMENSION 20
#define METHANE_SENSOR_VOLTAGE 3.3
#define METHANE_SENSOR_I_ON_WRITE 0.35
#define METHANE_SENSOR_T_ON_WRITE 6
#define METHANE_SENSOR_I_ON_READ 0.3
#define METHANE_SENSOR_T_ON_READ 6
#define METHANE_SENSOR_I_IDLE 0.002
